apiVersion: argobase/v1
kind: Application
metadata:
  name: myapp-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RodrigoSpano/argocd-appconfig-base.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

# this would create automatically create ns that doesn't exists like 'myapp'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

# automatically sync app
    automated:
      selfHeal: true
      prune: true
# prune true delete resources in the cluster if they are deleted in argocd
